# Getting, Cleaning, Exporting Data
Source: [kaggle](https://www.kaggle.com/datasets/smadler92/nfl-pfr)
The Dataset comes in multiple Tables that will need to be merged. We have Data from 1960 up until 2021 (but only two games from 2021, so it should be cut to 2020). These tables are organized:
* By Team Folder
    * 4 Files - Roster, Stats by Year, Weekly Odds, Weekly Scores
    * Weekly Injuries Folder
        * Each Year (2009-2021)
* Weather File

Want to be working with the weeklly scores from each team, adding a new column for the team name, and adding them to a DataFrame which will contain all teams data.

In [10]:
# Libraries
import pandas as pd # working with DataFrames
import numpy as np # linear algebra
import os #navigating the folders and files
import glob
from pathlib import Path

Need to Creating a Function that will navigate through our team folders (Ex: ATL)

In [11]:
# Extract teams and filenames from data folder
csv_files = [] # Empty list to store the file names
teams = [] # empty list to hold all team abbreviations
for filename in Path('data/NFLML').glob('**/* WeeklyScores All Years.csv'):
    csv_files.append(filename)
    team_abr = str(filename).split(' ')[0].split('\\')[3] # Only selects the team abbreviation from the file name
    teams.append(team_abr)

In [12]:
# Function for pulling csv files and adding to single dataframe
def join_frames(files, teams):
    
    data = [] #empty list to store the dataframes
    
    #loop through index up to 32
    for i in range(len(teams)):
        print(f"Getting Weekly Scores for {teams[i]}") # verbose
        team_df = pd.read_csv(files[i], index_col=0)
        team_df['Team'] = teams[i] # new column for each DataFrames associated team
        data.append(team_df)
    
    df = pd.concat(data, axis=0)
    return df

In [13]:
df = join_frames(csv_files,teams)

Getting Weekly Scores for ATL
Getting Weekly Scores for BUF
Getting Weekly Scores for CAR
Getting Weekly Scores for CHI
Getting Weekly Scores for CIN
Getting Weekly Scores for CLE
Getting Weekly Scores for CLT
Getting Weekly Scores for CRD
Getting Weekly Scores for DAL
Getting Weekly Scores for DEN
Getting Weekly Scores for DET
Getting Weekly Scores for GNB
Getting Weekly Scores for HTX
Getting Weekly Scores for JAX
Getting Weekly Scores for KAN
Getting Weekly Scores for MIA
Getting Weekly Scores for MIN
Getting Weekly Scores for NOR
Getting Weekly Scores for NWE
Getting Weekly Scores for NYG
Getting Weekly Scores for NYJ
Getting Weekly Scores for OTI
Getting Weekly Scores for PHI
Getting Weekly Scores for PIT
Getting Weekly Scores for RAI
Getting Weekly Scores for RAM
Getting Weekly Scores for RAV
Getting Weekly Scores for SDG
Getting Weekly Scores for SEA
Getting Weekly Scores for SFO
Getting Weekly Scores for TAM
Getting Weekly Scores for WAS

In [14]:
df.tail()

,Week,Day,Date,Time,Outcome,OT,Rec,Home,Opp,Score_Tm,...,Defense_1stD,Defense_TotYd,Defense_PassY,Defense_RushY,Defense_TO,Year,Expected Points_Offense,Expected Points_Defense,Expected Points_Sp. Tms,Team
1363,14,Sun,December 12,1:00PM ET,NaN,False,NaN,True,Dallas Cowboys,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1364,15,Sun,December 19,1:00PM ET,NaN,False,NaN,False,Philadelphia Eagles,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1365,16,Sun,December 26,8:20PM ET,NaN,False,NaN,False,Dallas Cowboys,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1366,17,Sun,January 2,1:00PM ET,NaN,False,NaN,True,Philadelphia Eagles,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1367,18,Sun,January 9,1:00PM ET,NaN,False,NaN,False,New York Giants,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS

In [16]:
df.loc[df['Year']==2021]

,Week,Day,Date,Time,Outcome,OT,Rec,Home,Opp,Score_Tm,...,Defense_1stD,Defense_TotYd,Defense_PassY,Defense_RushY,Defense_TO,Year,Expected Points_Offense,Expected Points_Defense,Expected Points_Sp. Tms,Team
918,1,Sun,September 12,1:00PM ET,L,False,0-1,True,Philadelphia Eagles,6.0,...,24.0,434.0,261.0,173.0,NaN,2021,-12.48,-13.14,2.36,ATL
919,2,Sun,September 19,4:05PM ET,L,False,0-2,False,Tampa Bay Buccaneers,25.0,...,21.0,341.0,259.0,82.0,1.0,2021,-15.96,-8.63,0.72,ATL
920,3,Sun,September 26,1:00PM ET,NaN,False,NaN,False,New York Giants,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,ATL
921,4,Sun,October 3,1:00PM ET,NaN,False,NaN,True,Washington Football Team,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,ATL
922,5,Sun,October 10,9:30AM ET,NaN,False,NaN,True,New York Jets,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1363,14,Sun,December 12,1:00PM ET,NaN,False,NaN,True,Dallas Cowboys,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1364,15,Sun,December 19,1:00PM ET,NaN,False,NaN,False,Philadelphia Eagles,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1365,16,Sun,December 26,8:20PM ET,NaN,False,NaN,False,Dallas Cowboys,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1366,17,Sun,January 2,1:00PM ET,NaN,False,NaN,True,Philadelphia Eagles,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS
1367,18,Sun,January 9,1:00PM ET,NaN,False,NaN,False,New York Giants,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,WAS

We can see above that the tail end of our DataFrame conatins many NaN values. This is due to the dataset containing up until the year 2021, yet only having data on the first two games of that season. Therefore, I will be dropping all rows from the 2021 season.